version: '3'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    ports:
     - "5432:5432"
    volumes:
     - postgis-data:/var/lib/postgresql/data
     - c:/dev/docker/data-loader/postgis-data:/postgis-loader
  geoserver:
    image: "thinkwhere/geoserver"
    ports:
      - "8085:8080"
    volumes:
      - c:/dev/docker/data-loader/geoserver-data:/opt/geoserver/data_dir
    environment:
      - "GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver_8085.log"
    depends_on:
      - postgis
  trex:
    build:
      context: .
      dockerfile: Dockerfile.trex
    volumes:
      - c:/dev/docker/data-loader/t-rex:/t-rex
    ports:
      - "6868:6767"
    depends_on:
      - postgis
volumes:
  postgis-data:
